[package]
name = "fuzzyfastq-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
fastq = { git = "https://github.com/MLKaufman/fastq-rs", branch = "master"}
flate2 = "1.0.28"
