[package]
name = "fuzzyfastq-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
fastq = "0.6.0"
flate2 = "1.0.28"
